#!/usr/bin/env python3

import sys
import io
import unicodedata

if len(sys.argv) != 2:
	print('Usage: unc <filename>')
	exit(-1)

fn = sys.argv[1]
with open(fn) as file:
	text = file.read()

with open(fn + '_nfc', 'w') as nfcOut:
	nfcOut.write(unicodedata.normalize('NFC', text))

with open(fn + '_nfkc', 'w') as nfkcOut:
	nfkcOut.write(unicodedata.normalize('NFKC', text))

with open(fn + '_nfd', 'w') as nfdOut:
	nfdOut.write(unicodedata.normalize('NFD', text))

with open(fn + '_nfkd', 'w') as nfkdOut:
	nfkdOut.write(unicodedata.normalize('NFKD', text))
